const jargon = {
  IT: 'Information Technology',
  ICT: 'Information and Communication Technology',
  programma: 'Een reeks van instructies die kan uitgevoerd worden door een computer om een specifieke taak uit te voeren',
  programmeren: 'Het ontwerpen en bouwen van een computer programma om een specifieke taak uit te voeren',
  processor: 'Een computerchip die instaat voor het uitvoeren van instructies',
  CPU: 'Central Processing Unit, of centrale process unit. Zie ook: processor',
  RAM: 'Random Access Memory, of gewoon werkgeheugen',
  cache: 'Een buffer om het lezen en/of schrijven van gegevens te versnellen',
  bottleneck: 'Beeldspraak om uit te drukken dat een system beperkt wordt door de beperking van 1 component. Bottleneck is Engels voor flessenhals.',
  bitcoin: 'De bekendste cryptocurrency, in 2008 uitgevonden door de raadselachtige Satoshi Nakamoto',
  cryptocurrency: 'Een digitaal alternatief voor (door staten uitegeven) munten. Typisch gedecentraliseerd en gebaseerd op blockchain technologie',
  blockchain: 'Een lijst van records, gelinkt doordat elk blok de cryptografische hash van het voorgaande blok bevat',
  moederbord: 'De voornaamste PCB (Printed Circuit Board) in een computer dat alle componenten verbindt',
  SSD: 'Solid State Drive',
  input: 'Invoer, of wat in een programma of computer gaat',
  output: 'Uitvoer, of wat uit een programma of computer komt',
  cores: 'Een multi-core processor heeft meerdere cores die elk zelfstandig operaties kunnen uitvoeren. Cores zijn als verschillende mini-processoren in dezelfde processor chip',
  TCP: 'Transport Connection Protocol',
  flashing: 'Het (over)schrijven van firmware op een speciale firmware chip',
  'haptische feedback': "Feedback die je kan voelen, zoals bij een vibrerende controller van een spelconsole, of de valse 'klik' die sommige touchpads genereren",
  UI: 'User Interface',
  UX: 'User Experience',
  'zwarte doos': 'Beeldspraak om uit te drukken dat de interne werking van een systeem niet gekend is of hoeft te zijn. We beschouwen alleen de inputs en outputs',
  'neurale netwerken': 'Een manier om data te verwerken die vaak synoniem staat met artificiele intelligentie',
  'volatiel geheugen': 'Geheugen dat onder stroom moet staan om zijn informatie te behouden',
  'harde schijf': 'Een fysieke disk voor de opslag van gegevens',
  'floppy disk': 'Een wisselbare disk voor de opslag van gegevens. Ook diskette genoemt',
  LAN: 'Local Area Network',
  WAN: 'Wide Area Network',
  UTP: 'Unshielded Twisted Pair, is een type kabel gebruikt in Ethernet en telefonie',
  Ethernet: 'Een netwerkstandaard waarmee computers in een LAN met elkaar communiceren',
  fiber: 'Van fiberoptics, een glasvezel kabel of verbiding',
  switch: 'Een toestel dat verschillende computers op het netwerk met elkaar verbindt',
  backbone: 'Een netwerk dat netwerken verbindt over grote afstand,  letterlijk ruggengraat',
  bit: "Een 'binaire digit', de basisunit van opslag in een computer die 1 of 0 kan bevatten",

}

module.exports = jargon


